AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    99168c3d-6818-4f56-b29f-162380b8e99a:
      size:
        width: 60
        height: 60
      position:
        x: 360
        'y': 80
      z: 1
      embeds: []
      isassociatedwith:
        - f861f418-7451-4c61-85e3-3f4ff84d66cb
    5ef5d669-e5a1-4173-b779-b2ed4af35b39:
      size:
        width: 60
        height: 60
      position:
        x: 200
        'y': 90
      z: 1
      embeds: []
      dependson:
        - 50c52a7a-53c6-46cd-98bf-da4787b4568d
        - 99168c3d-6818-4f56-b29f-162380b8e99a
    50c52a7a-53c6-46cd-98bf-da4787b4568d:
      size:
        width: 60
        height: 60
      position:
        x: 30
        'y': 100
      z: 1
      embeds: []
    ff3892f4-66ba-42a9-8a2b-00ae68d7485f:
      size:
        width: 60
        height: 60
      position:
        x: 30
        'y': 170
      z: 1
      embeds: []
    919716c8-4974-4ddd-a24d-f9fd2200a7f1:
      size:
        width: 60
        height: 60
      position:
        x: 200
        'y': 170
      z: 0
      embeds: []
      dependson:
        - ff3892f4-66ba-42a9-8a2b-00ae68d7485f
        - 6a4bbb58-9b27-4185-bcd1-4968fdfef6c8
    f861f418-7451-4c61-85e3-3f4ff84d66cb:
      size:
        width: 60
        height: 60
      position:
        x: 470
        'y': 80
      z: 0
      embeds: []
    d3f03a86-d8e9-405a-9a6b-727dd5320be3:
      size:
        width: 60
        height: 60
      position:
        x: 460
        'y': 170
      z: 0
      embeds: []
    6a4bbb58-9b27-4185-bcd1-4968fdfef6c8:
      size:
        width: 60
        height: 60
      position:
        x: 360
        'y': 170
      z: 0
      embeds: []
      isassociatedwith:
        - d3f03a86-d8e9-405a-9a6b-727dd5320be3
    d6a51393-6865-40de-99ef-fc7a99b39746:
      size:
        width: 60
        height: 60
      position:
        x: 350.3143503829611
        'y': 285.76549698326784
      z: 0
      embeds: []
    aac53e5f-9e87-4280-a7bc-9030b912511b:
      size:
        width: 60
        height: 60
      position:
        x: 200
        'y': 270
      z: 0
      embeds: []
      dependson:
        - 919716c8-4974-4ddd-a24d-f9fd2200a7f1
        - 5ef5d669-e5a1-4173-b779-b2ed4af35b39
Resources:
  apidatalambdagetdata:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: 's3//${PROJECT_NAME}-bucket-general-files/api-func-deployment-package.zip'
      Description: ''
      MemorySize: 128
      Timeout: 300
      Role: 'arn:aws:iam::839712734073:role/apidata-lambda-ex'
      Environment:
        Variables:
          raw_data_bucket: apidata-bucket-rawjson
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 5ef5d669-e5a1-4173-b779-b2ed4af35b39
    DependsOn:
      - ApidataBucketRawjson
      - pipelinestatemachine
  ApidataBucketRawjson:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${projectName}-bucket-rawjson'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 50c52a7a-53c6-46cd-98bf-da4787b4568d
  ApidataBucketCsv:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${projectName}-transform'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ff3892f4-66ba-42a9-8a2b-00ae68d7485f
  jsontocsv:
    Type: 'AWS::Glue::Job'
    Properties:
      Name: gluejob1-apidata1
      Role: AWSGlueServiceRole-apidata1
      CreatedOn: '2023-05-02T21:28:11.014000+00:00'
      LastModifiedOn: '2023-05-02T21:28:11.014000+00:00'
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Command:
        Name: pythonshell
        ScriptLocation: 's3://apidata1-bucket-general-files/glujob1.py'
        PythonVersion: '3.9'
      MaxRetries: 0
      AllocatedCapacity: 0
      Timeout: 2880
      MaxCapacity: 0.0625
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 919716c8-4974-4ddd-a24d-f9fd2200a7f1
    DependsOn:
      - ApidataBucketCsv
      - gluerole
  gluemanagedpolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: d3f03a86-d8e9-405a-9a6b-727dd5320be3
  lambdamanagedpolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Version: 2012-10-17
      Statement:
        - Sid: VisualEditor0
          Effect: Allow
          Action:
            - 'events:PutEvents'
            - 'lambda:ListFunctions'
            - 'lambda:InvokeFunction'
          Resource: '*'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f861f418-7451-4c61-85e3-3f4ff84d66cb
  gluerole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Ref gluemanagedpolicy
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 6a4bbb58-9b27-4185-bcd1-4968fdfef6c8
  pipelinestatemachine:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
                - lambda.amazonaws.com
                - apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - !Ref lambdamanagedpolicy
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 99168c3d-6818-4f56-b29f-162380b8e99a
  statemachineexecutionrole:
    Type: 'AWS::IAM::Role'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: d6a51393-6865-40de-99ef-fc7a99b39746
  MyStepFunction:
    Type: 'AWS::StepFunctions::StateMachine'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: aac53e5f-9e87-4280-a7bc-9030b912511b
    Properties:
      TracingConfiguration:
        Enabled: true
      DefinitionString: !Sub >-
        { "Comment": "A description of my state machine", "StartAt":
        "lambdagetdata", "States": { "lambdagetdata": { "Type": "Task",
        "Resource": "arn:aws:states:::lambda:invoke", "Parameters": {
        "Payload.$": "$", "FunctionName":
        "arn:aws:lambda:${AWS::Region}:{AWS::AccountId}:function:${projectName}-lambda-getdata:$LATEST"
        }, "Retry": [ { "ErrorEquals": [ "Lambda.ServiceException",
        "Lambda.AWSLambdaException", "Lambda.SdkClientException",
        "Lambda.TooManyRequestsException" ], "IntervalSeconds": 2,
        "MaxAttempts": 6, "BackoffRate": 2 } ], "Next": "Choice",
        "TimeoutSeconds": 300, "ResultSelector": { "STATUS.$":
        "$.Payload.STATUS", "file_name.$": "$.Payload.file_name" } }, "Choice":
        { "Type": "Choice", "Choices": [ { "Variable": "$.STATUS",
        "StringEquals": "success", "Next": "Glue StartJobRun" }, { "Variable":
        "$.STATUS", "StringEquals": "failed", "Next": "Fail" } ], "Default":
        "Fail" }, "Glue StartJobRun": { "Type": "Task", "Resource":
        "arn:aws:states:::glue:startJobRun.sync", "Parameters": { "JobName":
        "gluejob1-${projectName}", "Arguments": { "--source_bucket":
        "${projectName}-bucket-rawjson", "--target_bucket":
        "${projectName}-transform", "--file_name.$": "$.file_name" } }, "Next":
        "Success" }, "Success": { "Type": "Succeed" }, "Fail": { "Type": "Fail"
        } } }
    DependsOn:
      - jsontocsv
      - apidatalambdagetdata
